services:
  - type: web
    name: pronosticador
    env: python
    buildCommand: "- pip install -r requirements.txt"
    startCommand: "gunicorn tiendaonline.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: pronosticador.settings
      - key: PYTHON_VERSION
        value: 3.10
